### ISSUE TITLE
Dist build fails from missing electron-widevinecdm

### ISSUE THREAD

**Issue by NovusTheory** [nirewen/discord-netflix#13]
I'm simply marking this issue to know for later (if I fix or if anyone else is up to fixing)

`npm run dist` => Running unpacked executable erors with no electron-widevinecdm
`npm run start` => Runs fine with electron-widevinecdm dependencies

The cause is because of `npmpd --no-save` which doesn't save the dependency of electron-widevinecdm which means the `dist` doesn't include it. This is on purpose to make sure the package.json isn't modified so all development environments work.

Solution: Use a specially crafted package.json (.gitignore) for builds

**Comment by haboutnnah** [comment]
Any updates?
