### ISSUE TITLE
Time Left

### ISSUE THREAD

**Issue by 3cmXD** [nirewen/discord-netflix#19]
Hi,

The Rich Presence is working flawessly but there fews things that should be optimized.

The APP is sometimes slow as hell but it doesn't bother that much just during the browsing catalog.

And my time left aren't working that's all.

The rest works like charm!

**Comment by Wist9063** [comment]
You have to clone the repo, not installing via. the installer.

**Comment by nirewen** [comment]
Time left is now a thing, see v1.0.6
