### ISSUE TITLE
It's not showing since update

### ISSUE THREAD

**Issue by anhxtaiii** [nirewen/discord-netflix#23]
Like the title says, since the recent update the app doesn't seem to functions as it used to be. 

![image](https://user-images.githubusercontent.com/8799430/43296556-0b3f476a-911a-11e8-9d17-e6e1c497f4c9.png)

Normally with a rich presence you shouldn't need to add it since it will be automatically detected but just to make sure i added but it didn't work as it should. 

![image](https://user-images.githubusercontent.com/8799430/43296588-360ab07e-911a-11e8-95ea-cd70876d05e3.png)

**Comment by nirewen** [comment]
It's not showing because the app is tring to get the icon from the Discord assets.
Since the icons changed, this can't be done. I'll have to add the new icons to the list. Unfortunately, I won't be able to add them all, cause there are 150 slots available and 192 new icons. This is very sad...

**Comment by anhxtaiii** [comment]
So is there gonna be an update for this anytime soon since its just not showing at all anymore,
