### ISSUE TITLE
UnhandledPromiseRejectionWarning - Discord update

### ISSUE THREAD

**Issue by Italicz** [nirewen/discord-netflix#24]
(node:4127) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error [RPC_CLIENT_ERROR]: 4000 child "activity" fails because [child "assets" fails because [child "small_image" fails because ["small_image" length must be less than or equal to 32 characters long]]]

This is the error im getting after running "npm start" since the latest discord update.

**Comment by NovusTheory** [comment]
This relates to #23 as the icons in Netflix updated which has a hash ID longer than 32 characters. The Discord app @nirewen has needs to have the icons updated and names.

**Comment by NovusTheory** [comment]
@nirewen I believe this can be closed now since the issue was fixed in #25 (and your own commit which changed the method of what I put in)
