### ISSUE TITLE
1.0.6 release missing installer?

### ISSUE THREAD

**Issue by NovusTheory** [nirewen/discord-netflix#26]
Was release 1.0.6 meant to have the installer missing from the assets? The rest of the releases have an installer. Unless I'm missing something here it doesn't seem to contain it.

**Comment by nirewen** [comment]
I'm working on it. Apparently electron-widevinecdm is not found in the installer, I don't know why.

**Comment by nirewen** [comment]
Ok, apparently when you added dependencies for linux, darwin and win32, you forgot to pull the package-lock.json. Everything is messed up in my end. Trying to fix everything...

**Comment by nirewen** [comment]
Installer added.

**Comment by NovusTheory** [comment]
@nirewen That was actually on purpose because of an issue someone had here #8 which led to the breaking of windows builds so I opted to change the package json to install either of the widevine for the proper platform. I'd recommend not having pushed the package json update and instead manually update it for your local builds but not to put it on the repo. An active issue to resolve making `dist` work is #13
