### ISSUE TITLE
"Browsing the catalogs" when watching something.

### ISSUE THREAD

**Issue by dexev** [nirewen/discord-netflix#3]
Hi, I'm experiencing an issue where the state won't update from browsing the catalogs to what I'm currently watching. I've tried running both applications as administrators, downgrading to a previous version and reinstalling both applications, nothing seems to work.

A little bit of help would be greatly appreciated.

https://i.imgur.com/lcoubRC.png

**Comment by dexev** [comment]
It appears I've got this working after many attempts, you can close this now cheers!

**Comment by MJ94** [comment]
@dexev @nirewen Any idea how this was resolved? I'm having the same issue too.
