### ISSUE TITLE
Support for 1080p netflix

### ISSUE THREAD

**Issue by haboutnnah** [nirewen/discord-netflix#32]
This can be done with a Chrome extension: https://github.com/truedread/netflix-1080p

**Comment by nirewen** [comment]
It's not possible to add Chrome extension to an Electron application. But I'll take a look and maybe reverse engineer it to implement.

**Comment by haboutnnah** [comment]
Fair enough and thank you

**Comment by nirewen** [comment]
Though this should be already possible... Do you have HD enabled (High) in https://www.netflix.com/HdToggle?

**Comment by haboutnnah** [comment]
Is there a way to check stats of the video in the player? What you linked seems to have helped though, but I'm not sure it's the same quality as the one in chrome

**Comment by nirewen** [comment]
Should be. Electron is chromium based. I don't know how to check the stats of the video...

**Comment by haboutnnah** [comment]
I'm aware, yeah, but I dunno if it looks the same as chrome with the extension, and I don't know how to check without needing another extension. 

I suppose you could monitor network traffic and see the file size transmitted? I don't know how to though

**Comment by nirewen** [comment]
You can use a proxy interceptor but I don't know any

**Comment by haboutnnah** [comment]
Ah okay

**Comment by nirewen** [comment]
Reply here again if you see it's not 1080p yet

**Comment by haboutnnah** [comment]
I tested with glasswire and it uses way less data

**Comment by secw** [comment]
> Though this should be already possible... Do you have HD enabled (High) in https://www.netflix.com/HdToggle?

This only do 720p max or 3k bitrate if you check it with ctrl+alt+shift+D
I've tried the 1080p extension in chrome and the bitrate goes to 5k
Tested with better call saul

It just would've been perfect for me if you could integrate this. Thank you for your work!

**Comment by michaldolinski28** [comment]
For me is still capped on 720p, no 1080p, not even saying about 4K

**Comment by OgnistyPoland** [comment]
any news?
