### ISSUE TITLE
Getting logged out

### ISSUE THREAD

**Issue by lollilol** [nirewen/discord-netflix#39]
is it normal to get logged out after closing the netflix application? when yes, please update it. When no please fix it.

thanks
love

**Comment by nirewen** [comment]
That's not normal... 
If you marked this box it should keep logged in after you close and open the app again
![image](https://user-images.githubusercontent.com/8761479/48453151-582a9b80-e799-11e8-97a4-d23ddde6d082.png)

**Comment by lollilol** [comment]
https://youtu.be/2PdSE01f0-4
hmm it looks a bit different, but it should work..

**Comment by lollilol** [comment]
it logs me out, even if i save the log in data. eventually a cookies problem

**Comment by lollilol** [comment]
no answer?

**Comment by nirewen** [comment]
This happened to me and I fixed by updating electron
The update will be released very soon, today or tomorrow

**Comment by lollilol** [comment]
okay thx for replying :P
