### ISSUE TITLE
full hd 1080p

### ISSUE THREAD

**Issue by nielrds** [nirewen/discord-netflix#44]
Olá, teria como liberar para full HD, fiquei feliz com o programa, mas fiquei desapontado por não ser fullHD, e isso faz muita diferença aqui, ou eu que nao sei como habilitar(no site da netflix já esta para ser exibido conteudo em alta qualidade)

Agradeço...
(outro probelma que tenho, eu sempre tenho que abrir e fechar e abrir de novo pro discord reconhecer o rich presence, nunca reconhece desde a primeira vez q eu abro, vc poderia me ajudar com isso tbm?)

Muito obrigado!

**Comment by nirewen** [comment]
Às vezes acontece do Discord não reconhecer de primeira mesmo... 
A versão 2.0.0 tem uma notificação que aparece quando não consegue. 
Você pode clicar nela pra tentar de novo (sim, entra em loop e se não consegue de novo, notifica de novo e de novo...)
Pra opção HD, eu já estou trabalhando nisso, mas por ora você pode tentar aumentar o bitrate da aplicação abertando simultaneamente as teclas <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Alt</kbd> + <kbd>S</kbd>.
Infelizmente, essa combinação deve ser aplicada a todo vídeo, ou seja, em todo episódio...
Logo logo estou lançando uma versão com suporte HD 1080p

**Comment by nielrds** [comment]
Obrigado meu amigo, fico feliz que você esteja trabalhando na versão com suporta a 1080p,
agradeço por disponibilizar esse aplicativo de forma gratuita para comunidade, muito obrigado mesmo!..
Acho que irei esperar a  versao 1080p, sinto muita diferença aqui de 720p pra 1080p, kkkk! pretende lançar isso ja na proxima versão? Se puder dizer +- uma previsão, eu ficaria muito feliz rsrs.

obrigado mais uma vez !

**Comment by nirewen** [comment]
Sim, talvez na próxima já tenha

**Comment by nielrds** [comment]
Obrigado mais uma vez brother, espero que saia logo, hehe, sou ansioso pra essas coisas,
mas obrigado por disponibilizar isso free pra comunidade, já que a bundon* da netflix nao faz, é bom que no mundo existam pessoas como voce que tomem essa iniciativa, isso é muito bacana. Obrigado!

**Comment by nielrds** [comment]
Meu querido, só uma pergunta, para "filmes" nao esta funcionando a exibição do titulo/min na legenda do discord? http://prntscr.com/lpds7b baixei novamente o programa aqui(mas aguardando uma versao 1080p futura) pra fazer uns testes, mas quando vejo filme nao sai dessa legenda ae.

abraçao

**Comment by nirewen** [comment]
Hm... Parece que a Netflix mudou o player e os elementos não são mais os mesmos. Vou aplicar um patch em alguns minutos (horas)

**Comment by nielrds** [comment]
vocè é o cara, parabéns! [1080p vem nessa? haha, abraço]

**Comment by nirewen** [comment]
About this issue and #32:

1080p support is **not** coming to discord-netflix. If you want high definition, choose Ultra HD, if your plan doesn't have the Ultra 4 option, then my app won't help you with that. 

Also, as this would apply to every video, every show and movie, this might bring issues about bandwidth usage which I don't want to cover, or even app taking very long to load a video due to slow connection or something, or even the app freezing everytime because the device is not fast enough to render the video in such high resolution. 

As my app was planned to be only a Netflix wrapper with Rich Presence support, it won't have a big Settings panel where you can choose to force 1080p or not, it's just a simple app, and you can even use it if you don't have Discord.

Quality options are up the customer and what Netflix thinks fits best for your connection.

**Comment by nielrds** [comment]
Olá, entao, 1080p é uma coisa, Ultra HD é outra, meu plano é o padrão que inclui FullHD, que seria 1080p. O plano UltraHD é para conteudo em 4k(que não é tudo), Enfim. Só para relatar, ainda continuo com o "problema" de estar assistindo uma serie e no discord esta aparecendo "Browsing ...in catalogs"....
Bom, é só uma deixa, não to reclamando de seu app, ele é muito bom, e é de graça, por ser de graça não to no direito de reclamar...e sim de agradecer! Mas mesmo assim, quero que saiba que ficaria muito feliz se vier com suporte 1080p futuramente(fullHD), eu to assistindo no EDGE enquanto isso, que tem suporte a tal. Sobre a internet, minha internet é 60 mega, aguenta bem a resolução até 4k(mas nao ta no meu plano essa).

Valeu!

**Comment by nirewen** [comment]
Edge e ChromeOS têm suporte a Full HD, mas como eu disse, forçar isso o tempo todo pode dar problemas. No Edge eles tem um manifesto e no ChromeOS é hardware.
A opção "alta" habilita chegar desde 1080p a 4k (no plano Ultra), enquanto a "média" chega ao seu máximo no 720p.
Como eu disse, eu não vou forçar tanto pelo limite, que no Brasil não tem, mas em outros países tem, então forçar sempre ser FullHD faria o limite de banda chegar ao limite rápido e a culpa seria minha por não dar uma opção de desabilitar, quanto pelo fato do plano não cobrir, e se ele não cobre eu não posso "piratear" uma resolução maior.
