### ISSUE TITLE
32-Bit Version Installer?

### ISSUE THREAD

**Issue by Talaldev** [nirewen/discord-netflix#47]
Hello!

I was wondering if it was possible to compile a 32-bit version installer? It would be highly appreciated, even though no one barely has 32-bit anymore and I think my species is getting rarer with every passing second.

Thank you in advance!

**Comment by nirewen** [comment]
The current released installer should work on both 64 and 32 bits. It is not working for you?

**Comment by Talaldev** [comment]
The previous version works just fine. However, the 2.0.0 version gives an error message that reads as follows: "64-bit windows system is required"

**Comment by nirewen** [comment]
The latest version includes a 32-bit installer along with a web installer (portable)
