### ISSUE TITLE
discord-netflix v2.0.1 not working

### ISSUE THREAD

**Issue by SooomS** [nirewen/discord-netflix#48]
Eu instalei a nova versão a 2.0.1 e não está aparecendo a Netflix no discord, perguntei a outras pessoas e também não está aparecendo para elas.

**Comment by nirewen** [comment]
Você habilitou mostrar o jogo que está jogando no Discord?
Vá nas ⚙️ Configurações do usuário > Game Activity > Mostrar o jogo que está sendo executado como seu status. 

Se mesmo assim, não funcionar, veja se o aplicativo da Netflix não envia nenhuma notificação. 
Se depois de 3 tentativas ele não conseguir conectar ao Discord, uma notificação vai aparecer, você pode clicar nela pra tentar de novo. 

Se ainda assim não conectar, verifique o console do Discord, pressionando as teclas <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>I</kbd> e clicando na aba Console, no topo. Verifique mensagens relacionadas a "RPC" ou "IPC". Se achar alguma dessas mensagens escrita em vermelho ou com "Error" escrito nela, responda com um print dessas mensagens aqui embaixo.

**Comment by SooomS** [comment]
Eu andei testando e de facto com versões mais antigas, aparece escrito "Error", quando instalei a versão mais recente, existe alguns números a cor vermelha, mas não tem mensagem de erro, sobre as notificações eu não recebi nenhuma D:

![screenshot_5](https://user-images.githubusercontent.com/42103361/50560868-d5d04980-0cfc-11e9-9164-6ccf26ce8499.png)

**Comment by nirewen** [comment]
Nesses logs é possível ver que a aplicação está emitindo a presença ao Discord, então se não está aparecendo, verifique as configurações do usuário.
