### ISSUE TITLE
WildVine component not working on 2.0.2 - Mac

### ISSUE THREAD

**Issue by mwdiers** [nirewen/discord-netflix#51]
When running the pre-packaged app, the WildVine component is either missing or broken on Mac. No movies will actually play. Netflix displays the "Missing Component" error.

macOS 10.14.2.

If I build from source and run with `npm run start` it works fine.

I cannot build an app, because the dist:mac script attempts to sign the app, and fails, because I do not have any developer certificates installed.

**Comment by NovusTheory** [comment]
Considering the developer does not have a Mac this might take some time to figure out. It's oddly strange that it works fine when you compile it yourself though.

The `dist:mac` should also work just fine without signing the app

**Comment by mwdiers** [comment]
Yeah, but the `dist:mac` script tells it to sign, so it just fails and doesn't finish. The app seems to work even though the signing errors, but it has the same problem as the pre-built binary. No Wildvine.

**Comment by DooMl** [comment]
Hey, same here on Lubuntu 18.04 using the AppImage release.

**Comment by feuerpanda** [comment]
Same on Manjaro Linux, whatever the latest is, due to using Arch.

**Comment by NovusTheory** [comment]
The issue has been identified and a fix should be coming soon. I've tested it and talked to Nirewen.

**Comment by nirewen** [comment]
Widevine is pointing to 7.0.0 on Mac and Linux as of 2.1.0 release
