### ISSUE TITLE
"Browsing : In the catalogs"

### ISSUE THREAD

**Issue by Byeler** [nirewen/discord-netflix#52]
Hello. I just got your discord/netflix software (thank you very much!).
So I'm watching the new season of that show "A Series of Unfortunate Events" but it ain't working well.

Any idea how to fix this?
Thank you very much!

![Screenshot](https://i.imgur.com/K7jvFA0.png)

**Comment by FortKnox1337** [comment]
Yeah I seem to be getting the same issue. Just stuck on "Browsing the Catalogs".

Only happening in the last few days.

**Comment by nirewen** [comment]
This might be due to my script being inaccurate at some point.
Another user came to my dms reporting this. He said after a few days (or reopens) the app managed to work, so it might be something with cache? (Even though I don't use cache for this????)
So, I think I'm gonna mark this as help wanted because I don't see the flaw in my script.

**Comment by Wist9063** [comment]
I'm actually working on fixing this issue. I believe that it's something to do with netflix's new UI and the way that how the info is fetched. (The second one is just a theory, I don't really have hard evidence.)

**Comment by FortKnox1337** [comment]
Okay it seems to be working again today. But it definately wasn't working last night when I was watching stuff.
![screenshot 202](https://user-images.githubusercontent.com/34667229/50727554-6ef3cb80-1114-11e9-8e81-aa7228478618.png)

**Comment by BreadHey** [comment]
I'm also having this issue. Sometimes it works, most of the time it doesn't.

**Comment by SgtBreadStick** [comment]
Also having same issue, but it is constantly on "Browsing - In the Catalogs"

**Comment by Wist9063** [comment]
So, it's seems like it's something to do with detecting interactivity. Does anyone know a better way of detecting interactivity?

**Comment by SunnySydeRamsay** [comment]
Also have problem, just now downloaded latest exe build

**Comment by DeToxX97** [comment]
Hey there.

I had the same issue, since im using a lower version: 2.0.0 the issue seems to be not there.

Might be an little bug in the app who knows.. just wanted to let you guys know :)

**Comment by alterlove** [comment]
I've the issue too. Hope you find a fix soon, and thanks for this amazing script.
