### ISSUE TITLE
"npm run dist" doesn't exist

### ISSUE THREAD

**Issue by ElFamosoKilluaah** [nirewen/discord-netflix#55]

**Comment by Wist9063** [comment]
You're supposed to do ` npm start` to start the program .

**Comment by ElFamosoKilluaah** [comment]
Yeah but my goal was to build an executable, and after my fail i saw that there is releases packages in this repo xd

**Comment by NovusTheory** [comment]
That command was removed when Travis CI was implemented. I'd suggest sticking to using the releases as you didn't seem to even bother looking at package.json.

**Comment by nirewen** [comment]
If you want to build the binaries for distribution, run `npm run dist:platform` (of course changing `platform` to win/mac/linux)
