### ISSUE TITLE
User agent customization

### ISSUE THREAD

**Issue by DooML** [nirewen/discord-netflix#56]
Can you please allow us to customize the user agent ? As the Ctrl + Shift + Alt + S combination works only in the following user agent : 

> Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

If you're wondering what is it, it's a [keyboard shortcut](https://user-images.githubusercontent.com/26717942/51092276-b07c1a80-1795-11e9-9917-87af862cf0d7.png) that allows editing the bitrate manually because sometimes the quality automatically drops even on good internet.

**Comment by Wist9063** [comment]
Can you explain more?

**Comment by NovusTheory** [comment]
I personally don't see a reason this is needed. Faking a user-agent is not a great idea as it *can* affect the webserver's responses. I've never personally had issues with Netflix changing quality unless the internet is having problems. This is the only time it does adjust automatically is when it *can't* do the bitrate.

**Comment by nirewen** [comment]
This combination used to work but Netflix removed it a while ago, so it doesn't work anymore. I don't think the User Agent will fix this since it's blocked in their side of the code

**Comment by NovusTheory** [comment]
@nirewen Thanks, I didn't know that it disabled the dev tools in the packaged version. I thought it was always disabled via programming it with the electron API.

**Comment by DooML** [comment]
It still works ( the combination ) in browsers using an extension, I made few tests and realized it's completely irrelevant to the user agent. Instead, [this](https://chrome.google.com/webstore/detail/netflix-1080p/cankofcoohmbhfpcemhmaaeennfbnmgp/) makes it work, you can check by yourself; or maybe alternatively offer a menu to manually edit the bitrate from the wrapper?

[proof](https://user-images.githubusercontent.com/26717942/51876434-dc3bfa80-2368-11e9-8a26-8e6656b77a32.png)

**Comment by nirewen** [comment]
I know this extension, and tried to implement in my app before. It changes the original script to a proxied version which still includes the combo.

As I said, I tried to implement this before, but it's very hard to do using Electron and I couldn't make it perfect. When using a browser, developers can rely on chrome's functions, while in Electron I can't.
