### ISSUE TITLE
Netflix WebSetup v2.1.0

### ISSUE THREAD

**Issue by DarkHell-France** [nirewen/discord-netflix#61]
When starting Netflix v2.1.0 (for the first time), i have this error. Can you do smth about that ?
![screenshot_1](https://user-images.githubusercontent.com/45236214/53291674-671ce300-37b7-11e9-8eb6-2b40f802a316.png)

**Comment by nirewen** [comment]
Oh, my bad! I forgot release tags should include the `v` now. If you run the installer again, it should work. Sorry for that

**Comment by DarkHell-France** [comment]
It works ! Thank you very much !
