### ISSUE TITLE
Title Error

### ISSUE THREAD

**Issue by DarkHell-France** [nirewen/discord-netflix#62]
When watching a show (in this case, Overlord), it shows the title of the episode at the 2nd AND the 3rd line. It also says "Interactive video", even if it isn't.
![screenshot_1](https://user-images.githubusercontent.com/45236214/53292081-874fa080-37bd-11e9-9ddb-5e2baa5f7265.png)

**Comment by nirewen** [comment]
@Wist9063 what's this?

**Comment by nirewen** [comment]
Ah right, `innerText`... I'll be fixing this soon

**Comment by DarkHell-France** [comment]
Okay, thank you for you fast reply !

**Comment by nirewen** [comment]
This has been fixed as of #64
