### ISSUE TITLE
Rich Presence not registering.

### ISSUE THREAD

**Issue by howmanysmall** [nirewen/discord-netflix#66]
My girlfriend has been having issues with this. It just shows that she's playing Netflix, without any indication of what she's watching. I have tried everything to figure out why it's not working, but nothing has worked.

![image](https://user-images.githubusercontent.com/26746527/53689489-84503500-3d14-11e9-921b-d679133cb5cc.png)

**Comment by nirewen** [comment]
Can you ask her to type <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>I</kbd> and click the `Console` tab?

**Comment by howmanysmall** [comment]
It seemed to be fixed by rebooting. Sorry for wasting your time.
